### ISSUE TITLE
New lesson?

### ISSUE THREAD

**Issue by mnivoliez** [Nercury/rust-and-opengl-lessons#1]
Hello, your work is really inspiring and I used it to start a project on my own. Are you going to continue it? I saw lesson-08-Next in the repo. If you are, do you need help? Could I be of some use?
Anyway, thank you for what you have already done.

**Comment by Nercury** [comment]
Hello, I am glad to hear it! The new lessons are certainly planned, however I got a bit sidetracked by another project. For the help, I welcome any feedback and help on editing the lessons (the existing lessons are very lightly edited). If some part of tutorial was unclear, too handwavy, or maybe unnecessarily detailed, I would really like to know.

**Comment by mnivoliez** [comment]
Could I ask why did you use sdl2 and not glutin? I think it could make the startup more straightforward since there is no need to configure much in cargo.toml than just add the dependencies. Also, the sdl compilation may require external dependencies that might get in the way of getting started with opengl in rust.

**Comment by Nercury** [comment]
No other reason than me writing this from the perspective of readers coming from C/C++ gamedev world with SDL there being pretty much standard and battle-tested. I wanted to show that it is possible to set SDL up with Rust and have a nicer API. And I agree that some may get burned by the complexity of third-party dependencies. Oh well.

**Comment by Nercury** [comment]
New lessons are here, and more will be added until we build a reasonable renderer.
