### ISSUE TITLE
No available video device

### ISSUE THREAD

**Issue by sergiuchuckmisha** [Nercury/rust-and-opengl-lessons#10]
OS: Ubuntu 18.04

just cloned repo, installed `cmake` and, according to [instruction from readme](http://nercury.github.io/rust/opengl/tutorial/2018/02/08/opengl-in-rust-from-scratch-01-window.html#initializing-sdl)
installed: 
[libsdl2-dev](https://github.com/Rust-SDL2/rust-sdl2#linux)

and finally command 
`cargo run` in `lesson-01` gives error:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "No available video device"', src/libcore/result.rs:1009:5`

Googling didn't help.

May you suggest what is wrong?

**Comment by Nercury** [comment]
It is the SDL issue, can't help you here.

Try googling "SDL No available video device".

Some suggestions that pop up is to install packages `xorg-dev` and `ia32-libs`.
