### ISSUE TITLE
There is a spelling mistake in your blog

### ISSUE THREAD

**Issue by jcyongqin** [Nercury/rust-and-opengl-lessons#3]
[opengl-in-rust-from-scratch-03-compiling-shaders](http://nercury.github.io/rust/opengl/tutorial/2018/02/10/opengl-in-rust-from-scratch-03-compiling-shaders.html)
>Add **trangle.vert** to src:
>>(**traingle.vert**)
#version 330 core
layout (location = 0) in vec3 Position;
void main()
{
    gl_Position = vec4(Position, 1.0);
}

code with bold may be a spelling mistake.

**Comment by Nercury** [comment]
Thanks!
