### ISSUE TITLE
Correct code on lesson 6?

### ISSUE THREAD

**Issue by felipellrocha** [Nercury/rust-and-opengl-lessons#5]
Hey,

After many tries, I could not get lesson 6 to compile.

I get this error:
```
➜  thrones git:(master) ✗ cargo run
   Compiling gl v0.1.0 (file:///Users/fllr/Development/thrones/lib/gl)
error[E0432]: unresolved import `bindings::Gl`
  --> lib/gl/src/lib.rs:10:9
   |
10 | pub use bindings::Gl as InnerGl;
   |         ^^^^^^^^^^^^^^^^^^^^^^^ no `Gl` in `bindings`

warning: unused import: `std::rc::Rc`
 --> lib/gl/src/lib.rs:6:5
  |
6 | use std::rc::Rc;
  |     ^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `std::ops::Deref`
 --> lib/gl/src/lib.rs:7:5
  |
7 | use std::ops::Deref;
  |     ^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `gl`.

To learn more, run the command again with --verbose.
```

When I have this written down:

```
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

use std::rc::Rc;
use std::ops::Deref;

pub use bindings::*;
pub use bindings::Gl as InnerGl;
```

Any ideas on what's wrong here?

**Comment by Nercury** [comment]
The build.rs script failed to generate bindings.rs in the output directory.
Also older cargo did not used to pick up "build.rs" file automatically, you
had to write build = "build.rs" in Cargo.toml.

I suggest to take a step back and first do the same the 'gl' crate does
(the one available in crates.io). Once you get the bindings included, you
can start wrapping them inside Rc wrapper.

**Comment by felipellrocha** [comment]
Which cargo version should I be using (minimum)?

**Comment by felipellrocha** [comment]
> However, if we tried to use a reference to gl::Gl in our Program struct, we would quickly encounter few issues:

> (example, wait, don’t do this)

```
impl Program {
    pub fn from_shaders(gl: &gl::Gl, shaders: &[Shader]) -> Result<Program, String> {
        // use "." instead of "::"
        let program_id = unsafe { gl.CreateProgram() }; 
        
        ...
    }
}
```

Ok. I finally got it working last night. I figured out that part that was confusing. Essentially I needed to convert all `gl::` to `gl.` calls.

The confusing part was that above of where you say `// use "." instead of "::"` you also say `(example, wait, don’t do this)`, and you never go back to explain what part you *should* or *should not* do.

**Comment by Nercury** [comment]
It is a bit confusing, because I tried to demonstrate 3 alternative ways to do things. I agree thought that the lesson 6 is not as good or motivated as it should be. This series is experimental (I am writing it as I go), and I plan on huge rewrite when I finish it, so these kind of issues are good to know! Keep them coming.
